### PR TITLE
COVID19 Tracker - React App

### PR DESCRIPTION
**Pull request by alonsofl**
### Summary
Created a web application to track covid19 information by consuming an API.

#### Details
- Created React components for Header, Homepage, and Details.
- Added React Router to the application.
- Added search queries using Router.
- Connected React and Redux.
- Created Redux store, actions, and reducers for Homepage and Details.
- Fetch data from the Narrativa API and stored it with a better structure, considering the information used.
- Added conditional component to the "Go Back" button.
- Added required style for the components following the design guidelines.
- Added redux and app unit tests.

> [Live Demo](https://covid19-tracker-alonsofalconi.netlify.app/)

### CODE REVIEW

**Review by mricanho — CHANGES_REQUESTED** [review]
Hi @alonsofl, 

Good job so far! Your work here is nearly done, great job with de design and icons, your code is clean and easy to follow, and you are fetching the data responsibly 🔥🔥

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

- [ ] You missed only one requirement, the filter category on the home page (hint: you can group the countries by continent and use a select category to deploy the continent of your choice, it's only an idea, you can implement whatever you want, once you add this you are good to go!

imagen


_Check the comments under the review._

- [ ] [OPTIONAL] You could retarget the onclick to not only the arrow, but the entire div, remember that this app it's a mobile one, this could improve the user experience.

imagen

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

goodjob

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mricanho** [comment]
Loom Video: : https://www.loom.com/share/b8d6f2f0cc57408da74df52a4562f2fd

**Review by mikenath223 — APPROVED** [review]
Hello there  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the PR thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alonsofl** [comment]
Thanks, guys!

**Pull request merged**
